"""added field is_opened on appeal

Revision ID: 0ed4a8f4ac93
Revises: 555fa4d66bc7
Create Date: 2025-11-25 11:41:14.061934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed4a8f4ac93'
down_revision: Union[str, Sequence[str], None] = '555fa4d66bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appeals', sa.Column('is_opened', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appeals', 'is_opened')
    # ### end Alembic commands ###
